version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: swapi_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
